Release v0.4.0 (#90)
* Add frames-per-minute setting (#89)

* use a ProcessPoolExecutor to allow predict work to be scheduled across cores

* add monitoring_frames_per_minute plugin setting defaulting to 30 (0.5 fps)

* pass frame per minute settings to predict worker

* initialize monitoring on a thread and use concurrent.futuresProcessPoolManager to distribute work to processes instead of managing 1 process

* add pn websocket relay to monitoring threads init

* fix loop initialization

* add honeycomb traces

* refactor predictor initialization to support pickling results across process boundary

* trace predictions

* clean up proc ref

* Append to or initialize LD_LIBRARY_PATH (#91)

* move lib/ into module dir, append or initialize LD_LIBRARY_PATH

* remove cruft

* use os.environ.getenv locator

* Revert "use os.environ.getenv locator"

This reverts commit 527efa2db9ca9c20590ed92cb0792344a3c7dc35.

* add logging for LD_LIBRARY_PATHS var

* lint

* fixup library paths

* remove vendored libatlas3 library

* Bump version: 0.3.4 → 0.4.0

* update login url; closes #87

* fixes CI test failure: ImportError: cannot import name 'ThreadLocalPredictor' from 'octoprint_nanny.predictor'

* update README

* fixes ci test failure:  TypeError: __init__() missing 1 required positional argument: 'halt'